### ISSUE TITLE
Completion sources not showing

### ISSUE THREAD

**Issue by mel10c** [dburian/cmp-markdown-link#1]
Really like this idea, have being waiting for long!

If I understand correctly (correct me if I am wrong), this plugin enables **filename** completion with the trigger `[` or `[[`
- Eg. When I type `[[`, following with filenames under the directory, I should be able to see the file names showing in my cmp drop list right?

I was not able to get this working, I tried disabling the autopair plugin, still no luck. Can you please provide with a little more details in terms how to trigger the completion or is there any other additional config to do after installing and adding to the cmp sources. 

Really looking forward for it, thank you!

**Comment by dburian** [comment]
Hi,

the style of links you are referring to is (as far as I know) called wiki-style links and it is an extension of the original markdown syntax. I am not familiar with that format but i know it is becoming increasingly popular.

Right now the plugin only supports reference links...
```markdown
[link_identifier]: ./notes/some_folder/note.md

[link label][link_identifier]
```

So after you type `[asdfsdf][` a cmp completion should kick in with the filename completion. After you select a file the plugin creates an identifier of the link, based on the path, and adds it to the bottom or top of the document as a reference if it isn't there already.

Right now I have lots of work, but I will look into wiki-style links in the future. I've updated the readme, but feel free to ask if you are still struggling to get the reference links to work.

**Comment by mel10c** [comment]
Oh, I see now, thanks for relying! Looking forward for the wiki links support 👍
